CREATE TABLE Users (
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    joined TEXT NOT NULL,
    role INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE Artists (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE Songs (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    artist INTEGER NOT NULL REFERENCES Artists (id) ON UPDATE CASCADE ON DELETE CASCADE,
    added_by INTEGER NOT NULL REFERENCES Users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    added_at TEXT NOT NULL,
    duration TEXT NOT NULL
);
